# Generated by Django 4.2.16 on 2024-09-15 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estado_Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genero_Literario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('autor', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('portada', models.ImageField(upload_to='covers/%Y/%m/%d')),
                ('id_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginarioweb.autor')),
                ('id_editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginarioweb.editorial')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_registro', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField(null=True)),
                ('resenia', models.TextField(blank=True, null=True)),
                ('id_estado_libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginarioweb.estado_libro')),
                ('id_libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginarioweb.libro')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginarioweb.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_Genero_Literario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_genero_literario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginarioweb.genero_literario')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginarioweb.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('id_libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginarioweb.libro')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginarioweb.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Libro_Genero_Literario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_genero_literario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginarioweb.genero_literario')),
                ('id_libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginarioweb.libro')),
            ],
        ),
    ]
